In [2]:
import pandas as pd
df = pd.read_csv("Resources/white.csv")
df

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year
0,Vermentino 2017,Italy,Toscana,Famiglia Castellani,3.8,25,5.65,2017
1,Ronco Broilo 2010,Italy,Colli Orientali del Friuli,Conte d'Attimis Maniago,4.3,25,44.90,2010
2,Weisser Schiefer s 2017,Austria,Südburgenland,Weinbau Uwe Schiefer,4.2,25,33.25,2017
3,Chardonnay 2018,Germany,Rheinhessen,Krämer - Straight,3.9,25,8.99,2018
4,Maganza Zibibbo 2018,Italy,Terre Siciliane,Luna Gaia,3.9,25,8.60,2018
...,...,...,...,...,...,...,...,...
3759,Sauvignon Blanc 2019,New Zealand,Marlborough,Oyster Bay,4.0,4423,10.66,2019
3760,Vinho Verde Sweet N.V.,Portugal,Vinho Verde,Casal Garcia,4.0,4609,5.05,N.V.
3761,Sauvignon Blanc 2018,New Zealand,Marlborough,Kim Crawford,3.9,5105,14.90,2018
3762,Sauvignon Blanc 2019,New Zealand,Marlborough,Hans Greyl,4.2,5817,7.75,2019
3763,Vinho Verde Branco N.V.,Portugal,Vinho Verde,Casal Garcia,3.7,62980,4.35,N.V.

In [3]:
df = df[df.Year != "N.V."]
df = df.drop(columns = "NumberOfRatings")

In [4]:
df.to_csv('scraped_White.csv', index=False)

In [5]:
dummies = pd.get_dummies(df["Name"])
dummies.head()
Counrty_dummies = pd.get_dummies(df["Country"])
Region_dummies = pd.get_dummies(df["Region"])
Winery_dummies = pd.get_dummies(df["Winery"])
empty_df = df.drop(columns=["Name", "Country", "Region", "Winery"])

In [6]:
df_scaled = pd.concat([empty_df, dummies, Region_dummies, Counrty_dummies, Winery_dummies], axis =1)
df_scaled.head()

,Rating,Price,Year,'Rosso & Bianco' Chardonnay 2016,'Rosso & Bianco' Chardonnay 2017,1000-Eimerberg Riesling Federspiel 2018,1000-Eimerberg Smaragd Riesling 2018,101 Rangs Pouilly-Fumé 2016,101 Riesling 2018,12 e Mezzo Malvasia del Salento 2019,...,Ziereisen,Zonin,Zonnebloem,Zýmē,d'Arenberg,de Ladoucette,di Lenardo,Álvarez y Díez,Ökonomierat Rebholz,Κτημα Τσελεπου (Ktima Tselepos)
0,3.8,5.65,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4.3,44.90,2010,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4.2,33.25,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3.9,8.99,2018,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3.9,8.60,2018,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [8]:
from sklearn.model_selection import train_test_split
X = df_scaled.drop(columns="Rating")
y = df_scaled["Rating"]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [9]:
model.fit(X, y)

LinearRegression()

In [10]:
LinearRegression()

LinearRegression()

In [11]:
predicted_y_values = model.predict(X)

In [12]:
copy_df = df.copy()

In [13]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
score = model.score(X, y, sample_weight=None)
r2 = r2_score(y, predicted_y_values)
mse = mean_squared_error(y, predicted_y_values)
rmse = np.sqrt(mse)
std = np.std(y)

# Print releveant metrics.
print(f"The score is {score}.")
print(f"The r2 is {r2}.")
print(f"The mean squared error is {mse}.")
print(f"The root mean squared error is {rmse}.")
print(f"The standard deviation is {std}.")

The score is 0.9854354302109968.
The r2 is 0.9854354302109968.
The mean squared error is 0.0010219714706821848.
The root mean squared error is 0.03196828851662511.
The standard deviation is 0.26489304500357924.